name: attendanceapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  google_fonts: ^4.0.3
  slide_to_act: ^2.0.1
  flutter_spinkit: ^5.2.1
  http: ^1.2.2
  intl: ^0.19.0
  geolocator: ^10.0.0
  device_info_plus: ^9.0.3
  shared_preferences: ^2.3.2
  permission_handler: ^10.0.0
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  connectivity_plus: ^3.0.3
  uuid: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

